POST http://localhost:3001/api/notes/
Content-Type: application/json

{ 
    "content": "Esta es una nueva nota por rest client VSCODE" ,
    "important": true,
    "userId": "621c420a668b1ad8ef51d0cc"
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{ 
    "content": "" ,
    "important": true
}